### ISSUE TITLE
Errors from example_finetune.py

### ISSUE THREAD

**Issue by aiscientist** [andi611/Mockingjay-Speech-Representation#5]
Hi,

I found one error from example_finetune.py

Traceback (most recent call last):
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-857a63065eaa>", line 1, in <module>
    loss = classifier(reps, torch.LongTensor([0, 1, 0]))
  File "/Users/user/pt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/user/github/Mockingjay-Speech-Representation/downstream/model.py", line 282, in forward
    loss = self.criterion(result, labels)
  File "/Users/user/pt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/user/pt/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/Users/user/pt/lib/python3.6/site-packages/torch/nn/functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/Users/user/pt/lib/python3.6/site-packages/torch/nn/functional.py", line 1836, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (1200) to match target batch_size (3).

It might be the simple issue, but for the reminder.

**Comment by andi611** [comment]
Thank you for the reminder!

We forgot to update this example code upon the update of other codes,
bugs have been fixed: https://github.com/andi611/Mockingjay-Speech-Representation/commit/c764e4b721bd43d459a2459396eb98261a7577ab
