### ISSUE TITLE
UnknownBackendTraceback and FileNotFoundError when using Google Colab

### ISSUE THREAD

**Issue by aviasd** [andi611/Mockingjay-Speech-Representation#7]
I tried to run the model on Google Colab.
After downloading and activating:
```
!git clone https://github.com/andi611/Mockingjay-Speech-Representation.git

import os
os.chdir("Mockingjay-Speech-Representation")

!pip3 install -r requirements.txt
```
When I am running this line from the [Downstream Task Instructions](https://github.com/andi611/Mockingjay-Speech-Representation/wiki/Downstream-Task-Instructions):

```
# using spectrogram as baseline
!python3 runner_mockingjay.py --train_phone
```

I am getting an error:
```
[TerminalIPythonApp] WARNING | GUI event loop or pylab initialization failed

UnknownBackendTraceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   2953         # Now we must activate the gui pylab wants to use, and fix %run to take
   2954         # plot updates into account
-> 2955         self.enable_gui(gui)
   2956         self.magics_manager.registry['ExecutionMagics'].default_runner = \
   2957             pt.mpl_runner(self.safe_execfile)

/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py in enable_gui(self, gui)
    512         if gui:
    513             self.active_eventloop, self._inputhook =\
--> 514                 get_inputhook_name_and_func(gui)
    515         else:
    516             self.active_eventloop = self._inputhook = None

/usr/local/lib/python3.6/dist-packages/IPython/terminal/pt_inputhooks/__init__.py in get_inputhook_name_and_func(gui)
     36 
     37     if gui not in backends:
---> 38         raise UnknownBackend(gui)
     39 
     40     if gui in aliases:

UnknownBackend: No event loop integration for 'inline'. Supported event loops are: qt, qt4, qt5, gtk, gtk2, gtk3, tk, wx, pyglet, glut, osx
/usr/local/lib/python3.6/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
/content/Mockingjay-Speech-Representation/utility/audio.py:19: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "runner_mockingjay.py", line 237, in <module>
    main()
  File "runner_mockingjay.py", line 110, in main
    from downstream.solver import Downstream_Trainer
  File "/content/Mockingjay-Speech-Representation/downstream/solver.py", line 24, in <module>
    from dataloader import get_Dataloader
  File "/content/Mockingjay-Speech-Representation/dataloader.py", line 25, in <module>
    from ipdb import set_trace
  File "/usr/local/lib/python3.6/dist-packages/ipdb/__init__.py", line 7, in <module>
    from ipdb.__main__ import set_trace, post_mortem, pm, run             # noqa
  File "/usr/local/lib/python3.6/dist-packages/ipdb/__main__.py", line 29, in <module>
    ipapp.initialize(['--no-term-title'])
  File "<decorator-gen-120>", line 2, in initialize
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ipapp.py", line 320, in initialize
    self.init_gui_pylab()
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/shellapp.py", line 213, in init_gui_pylab
    r = enable(key)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2950, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/pylabtools.py", line 309, in activate_matplotlib
    matplotlib.pyplot.switch_backend(backend)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 231, in switch_backend
    matplotlib.use(newbackend, warn=False, force=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py", line 1422, in use
    reload(sys.modules['matplotlib.backends'])
  File "/usr/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use("Agg")
[SOLVER] -  CUDA is available!
[SOLVER] -  Loading source data from ['train-clean-360'] from data/libri_mel160_subword5000
[SOLVER] -  Loading phone data from ['train-clean-360'] from data/libri_phone
Traceback (most recent call last):
  File "runner_mockingjay.py", line 237, in <module>
    main()
  File "runner_mockingjay.py", line 114, in main
    trainer.load_data(split='train', load='phone')
  File "/content/Mockingjay-Speech-Representation/downstream/solver.py", line 97, in load_data
    **self.config['dataloader']))
  File "/content/Mockingjay-Speech-Representation/dataloader.py", line 840, in get_Dataloader
    train_proportion=train_proportion if split == 'train' else 1.0)
  File "/content/Mockingjay-Speech-Representation/dataloader.py", line 248, in __init__
    super(Mel_Phone_Dataset, self).__init__(file_path, sets, bucket_size, max_timestep, max_label_len, drop, load)
  File "/content/Mockingjay-Speech-Representation/dataloader.py", line 54, in __init__
    tables = [pd.read_csv(os.path.join(file_path, s + '.csv')) for s in sets]
  File "/content/Mockingjay-Speech-Representation/dataloader.py", line 54, in <listcomp>
    tables = [pd.read_csv(os.path.join(file_path, s + '.csv')) for s in sets]
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'data/libri_mel160_subword5000/train-clean-360.csv' does not exist

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

There are 2 problems here.
1. The "UnknownBackendTraceback" at the top,
2. The "FileNotFoundError" at the bottom.

For both problems:
1. Is there a way to make it work with Google colab?
2. How can I load the data required for the training?

Thank you,

**Comment by andi611** [comment]
Hi,
to answer your questions:

1) For the first problem, although I'm not familiar with Google colab, but I believe the error was caused by this line: `matplotlib.use("Agg")`, since "Agg" is probably an `UnknownBackendTraceback` for Google colab. You might want to change the `matplotlib` backend to something suitable for Google colab or simply remove all the codes associated with `matplotlib`.

2) According to the error: `FileNotFoundError: File b'data/libri_mel160_subword5000/train-clean-360.csv' does not exist`, it looks like a simple path issue. You have to make sure you have the file `train-clean-360.csv` in this relative path: `data/libri_mel160_subword5000/train-clean-360.csv`. Note that `data/` should be under the same directory as `runner_mockingjay.py`.
If  not, follow the steps in https://github.com/andi611/Mockingjay-Speech-Representation/wiki/Mockingjay-Preprocessing-Instructions to generate them.

**Comment by aviasd** [comment]
Hi,
Thank you for your fast response.
When downloading [LibriSpeech](http://www.openslr.org/12/), there is no CSV file in the dataset.
I assume you created the CSV file yourself based on the data in the corpus.
How can we get the CSV file?
